[package]
name = "markdown-server"
version = "0.1.0"
edition = "2021"

[lib]
name = "server"
test = false
path = "src/server/mod.rs"

[dependencies]
hyper = "1.4.1"
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
